version: "3.9"

services: 
 db:
    image: mysql:8.0

    container_name: mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - app_network

backend:
    build:
      context: ./server

    container_name: nest_backend

    restart: always

    depends_on:
      - db

    env_file:
      - .env.${ENV}

    ports:
      - "3000:3000"

    networks:
      - app_network

frontend:
    build:
      context: ./client

    container_name: frontend_app

    restart: always

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:

